### ISSUE TITLE
Ampersand in name of User causing bullet-train to malfunction system-wide for that user

### ISSUE THREAD

**Issue by Roeefl** [SolidStateGroup/bullet-train-js-client#12]
Hello,

I'd like to report an issue that we've come across about a month ago (sorry for procrastinating on reporting this).

In our bullet-train configuration, we added a User named `369___H&R_Block`

Few days later they reported our app malfunctioning in a few different places.

We realized that the `&` in the user name was causing an issue during the .identify function of the package.

This caused the rest of our data received from our API to be broken as well.

Here's what we did to resolve it for the time being:
```
bulletTrain.identify('...some user name here...'.replace(/&/g, '_AND_'));
```

But we thought you guys would like to know about it.

By the way, big fans of bullet-train. 
Really great to use. Thank you

Roee, Webiya

**Comment by kyle-ssg** [comment]
Hi @Roeefl thanks for reporting this, glad to see that you're enjoying using Bullet Train!

I do seem to recall an encoding issue quite a while back when we started identifying users by email address in one of our projects, it sounds that this could potentially be the same issue.

I'll try the above out later and get back to you.

Thanks

**Comment by kyle-ssg** [comment]
Hi again, just following up on this. I believe we found and fixed this issue a few releases ago!

Code to test the case:
https://jsfiddle.net/amech1oL/3/

Project to validate the identity:
If you login to bullet-train.io under the demo account and navigate to the project.
https://bullet-train.io/project/766/environment/NmNahFWDJeemHWrQppa8fn/users

![image](https://user-images.githubusercontent.com/8608314/68162754-a7d91880-ff50-11e9-8d25-27e72711763d.png)

**Comment by Roeefl** [comment]
@kyle-ssg Thanks man! good to know that this had already been resolved. We'll remove our manual fix next week :)

**Comment by kyle-ssg** [comment]
No problem glad I could help!
