### ISSUE TITLE
"identify" does not work if string contains a dot

### ISSUE THREAD

**Issue by deividasm** [SolidStateGroup/bullet-train-js-client#5]
I have discovered, that this does not work:

`bulletTrain.identify("test.1");`

and this does work

`bulletTrain.identify("test_1");`

**Comment by deividasm** [comment]
I had a look at the "identify" implementation, and it is likely, that the issue is in the server, and not in the client.

**Comment by ssg-luke** [comment]
Hi @deividasm, yep this is a server issue. There is a PR that fixes this waiting to be merged here https://github.com/SolidStateGroup/bullet-train-api/pull/22
