### ISSUE TITLE
We are getting the Error with "Attempted to assign to readonly property" in React Native 

### ISSUE THREAD

**Issue by gowthamans268** [SolidStateGroup/bullet-train-js-client#7]
We are getting the error "Attempted to assign to readonly property" in React native.
While importing the using **import TestButton from "./bullet-train";** 
Is there any thing special we have to do while importing the component from the webpack bundled js file

**Comment by ssg-luke** [comment]
Hi there, are you trying to run the example? Or have you installed the module within your RN project?

If its the latter you import bullet train by doing `import bulletTrain from "react-native-bullet-train";`
